spring:
  profiles:
    active: dev
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    generate-ddl: true
    database: mysql
    database-platform: com.mhlab.br.config.CustomMySql5Dialect

